site_name: Dan's Second Brain

site_url: https://dbowling.github.io/kb
repo_url: https://github.com/dbowling/kb
edit_uri: edit/main/docs/
docs_dir: docs
theme: readthedocs

plugins:
  - search:
      indexing: 'full'

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - admonition: {}
  - codehilite
  - meta